name: ecommerce-chatbot
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Core ML & Data
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - pytorch=2.3.1
  - transformers=4.41.2
  - spacy=3.7.5
  - sentence-transformers=3.0.1
  - faiss-cpu=1.8.0
  - elasticsearch=8.13.0
  - nltk=3.8.1
  # API & Serving
  - fastapi=0.111.0
  - uvicorn=0.29.0
  - python-jose=3.3.0
  - passlib=1.7.4
  - spacy-lookups-data=1.0.5
  # Database & Storage Connectors
  - psycopg2=2.9.9
  - boto3=1.34.120
  - botocore=1.34.120
  - s3transfer=0.10.1
  - pip
  - pip:
      # Deployment & MLOps (better from pip)
      - mlflow==2.13.2
      - dvc[s3]==3.51.1
      - prefect==2.19.4
      - great-expectations==0.18.13
      # API extra
      - uvicorn[standard]
      # Dataset loader
      - datasets==2.19.1
      # Training frameworks
      - pytorch-lightning==2.4.0
      - lightning==2.4.0
      - torchmetrics==1.4.0
      - spacy==3.7.5